### ISSUE TITLE
Inventory rendering is broken in MCC

### ISSUE THREAD

**Issue by milutinke** [breadbyte/ConsoleInteractive#10]
![image](https://user-images.githubusercontent.com/441903/185986761-db004565-e603-43a4-be0c-33f0a4a17aa7.png)

The code has not been changed to my knowledge.

**Comment by breadbyte** [comment]
Already reported in the main repo as https://github.com/MCCTeam/Minecraft-Console-Client/issues/2111.

Will look into it as soon as I can.
